name: Yeetables
main: anon.def9a2a4.yeetables.YeetablesPlugin
version: ${version}
api-version: 1.21
author: You
description: Data-driven throwable items with configurable physics, abilities, and rendering.

commands:
  yeetables:
    description: Yeetables plugin commands
    usage: /yeetables <reload|list|give <item>>

permissions:
  yeetables.reload:
    description: Allows reloading the plugin configuration
    default: op
  yeetables.give:
    description: Allows giving custom items to yourself
    default: op
